[package]
name = "filum"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
windows = { version = "0.58.0", features = ["Win32", "Win32_Networking", "Win32_Networking_WinSock"] }
